import type { Metadata } from "next";
import { Geist_Mono, Montserrat, Yellowtail } from "next/font/google";
import "./globals.css";   

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

const yellowtail = Yellowtail({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-yellowtail",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
  className={`${montserrat.variable} ${yellowtail.variable} antialiased`}
>
  {children}
</body>
    </html>
  );
}
